[workspace]
members = ["projects/*"]
default-members = [
    "projects/unity-tools",
    "projects/unity-utils",
]
exclude = [
    "projects/.DS_Store",
]

[profile.release]
lto = true
panic = "abort"
